{
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "colab": {
   "name": "Copy of main.ipynb",
   "provenance": [
    {
     "file_id": "https://github.com/nicofirst1/MAMBRL/blob/main/colab/main.ipynb",
     "timestamp": 1634657735298
    }
   ]
  }
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "M59jsEGLOqx8"
   },
   "source": [
    "Check out [Vortana's tutorial](https://towardsdatascience.com/google-drive-google-colab-github-dont-just-read-do-it-5554d5824228) for the colab/github/drive integration.\n",
    "Most of the code is taken from his work."
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "12KDduLnEqSo",
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "status": "ok",
     "timestamp": 1634658264961,
     "user_tz": -120,
     "elapsed": 1376,
     "user": {
      "displayName": "Nicolò Brandizzi",
      "photoUrl": "https://lh3.googleusercontent.com/a-/AOh14Gi76aUrl4eyFBjn10jiRcK6PIlYlR0vK8QXTJPY=s64",
      "userId": "01196368906490631258"
     }
    },
    "outputId": "13b44025-81bb-4c0b-df83-a077294ec068"
   },
   "source": [
    "# Mount Google Drive\n",
    "from google.colab import drive # import drive from google colab\n",
    "\n",
    "ROOT = \"/content/drive\"     # default location for the drive\n",
    "print(ROOT)  \n",
    "drive.mount(ROOT, force_remount=True)"
   ],
   "execution_count": 28,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "/content/drive\n",
      "Mounted at /content/drive\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "M6Yk6v-FGWaq",
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "status": "ok",
     "timestamp": 1634658314163,
     "user_tz": -120,
     "elapsed": 288,
     "user": {
      "displayName": "Nicolò Brandizzi",
      "photoUrl": "https://lh3.googleusercontent.com/a-/AOh14Gi76aUrl4eyFBjn10jiRcK6PIlYlR0vK8QXTJPY=s64",
      "userId": "01196368906490631258"
     }
    },
    "outputId": "509c7513-ec4c-4b33-bcbf-8945d6b01633"
   },
   "source": [
    "# Clone github repository setup\n",
    "# import join used to join ROOT path and MY_GOOGLE_DRIVE_PATH\n",
    "from os.path import join  \n",
    "\n",
    "# path to your project on Google Drive\n",
    "MY_GOOGLE_DRIVE_PATH = \"MyDrive/ColabNotebooks\"\n",
    "# replace with your Github username \n",
    "GIT_USERNAME = \"nicofirst1\" \n",
    "# definitely replace with your\n",
    "GIT_TOKEN = \"{YOUR TOKEN}\"  \n",
    "# Replace with your github repository \n",
    "GIT_REPOSITORY = \"MAMBRL\" \n",
    "\n",
    "PROJECT_PATH = join(ROOT, MY_GOOGLE_DRIVE_PATH)\n",
    "\n",
    "# It's good to print out the value if you are not sure \n",
    "print(\"PROJECT_PATH: \", PROJECT_PATH)   \n",
    "\n",
    "# In case we haven't created the folder already; we will create a folder in the project path \n",
    "!mkdir \"{PROJECT_PATH}\"    \n",
    "\n",
    "GIT_PATH = \"https://\" + GIT_TOKEN + \"@github.com/\" + GIT_USERNAME + \"/\" + GIT_REPOSITORY + \".git\"\n",
    "print(\"GIT_PATH: \", GIT_PATH)"
   ],
   "execution_count": 30,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "PROJECT_PATH:  /content/drive/MyDrive/ColabNotebooks\n",
      "shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n",
      "mkdir: cannot create directory ‘/content/drive/MyDrive/ColabNotebooks’: File exists\n",
      "GIT_PATH:  https://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@github.com/nicofirst1/MAMBRL.git\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "v0W-pLgBNr2m",
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "status": "ok",
     "timestamp": 1634658113019,
     "user_tz": -120,
     "elapsed": 279,
     "user": {
      "displayName": "Nicolò Brandizzi",
      "photoUrl": "https://lh3.googleusercontent.com/a-/AOh14Gi76aUrl4eyFBjn10jiRcK6PIlYlR0vK8QXTJPY=s64",
      "userId": "01196368906490631258"
     }
    },
    "outputId": "9bfdbda4-c698-4ad8-b3a3-952c7d0c8ab0"
   },
   "source": [
    "% ls \"{PROJECT_PATH}\" "
   ],
   "execution_count": null,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "AyAXY6WVIfpu",
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 913
    },
    "executionInfo": {
     "status": "error",
     "timestamp": 1634658121337,
     "user_tz": -120,
     "elapsed": 280,
     "user": {
      "displayName": "Nicolò Brandizzi",
      "photoUrl": "https://lh3.googleusercontent.com/a-/AOh14Gi76aUrl4eyFBjn10jiRcK6PIlYlR0vK8QXTJPY=s64",
      "userId": "01196368906490631258"
     }
    },
    "outputId": "26852a72-ce1f-4f63-fca0-9b14a30ed608"
   },
   "source": [
    "# copy git repo in project path\n",
    "%cd \"{PROJECT_PATH}\"    \n",
    "!git clone \"{GIT_PATH}\"\n",
    "%cd \"{GIT_REPOSITORY}\""
   ],
   "execution_count": null,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-15-1925a96e7c14>\", line 2, in <module>\n",
      "    get_ipython().magic('cd \"{PROJECT_PATH}\"')\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2160, in magic\n",
      "    return self.run_line_magic(magic_name, magic_arg_s)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2081, in run_line_magic\n",
      "    result = fn(*args,**kwargs)\n",
      "  File \"<decorator-gen-84>\", line 2, in cd\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py\", line 188, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/magics/osm.py\", line 288, in cd\n",
      "    oldcwd = py3compat.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 1823, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/usr/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/usr/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/usr/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/usr/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/usr/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/usr/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    },
    {
     "output_type": "error",
     "ename": "FileNotFoundError",
     "evalue": "ignored",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "WEjMm4qiLc-4",
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "status": "ok",
     "timestamp": 1634658016946,
     "user_tz": -120,
     "elapsed": 2515,
     "user": {
      "displayName": "Nicolò Brandizzi",
      "photoUrl": "https://lh3.googleusercontent.com/a-/AOh14Gi76aUrl4eyFBjn10jiRcK6PIlYlR0vK8QXTJPY=s64",
      "userId": "01196368906490631258"
     }
    },
    "outputId": "7a53b0bc-9a4b-4f00-d4c3-59514fcacf4e"
   },
   "source": [
    "!pip install -r requirements.txt"
   ],
   "execution_count": null,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Collecting absl-py==0.14.0\n",
      "  Using cached absl_py-0.14.0-py3-none-any.whl (131 kB)\n",
      "Requirement already satisfied: astunparse==1.6.3 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (1.6.3)\n",
      "Requirement already satisfied: attrs==21.2.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (21.2.0)\n",
      "Requirement already satisfied: cachetools==4.2.4 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (4.2.4)\n",
      "Requirement already satisfied: charset-normalizer==2.0.6 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 5)) (2.0.6)\n",
      "Requirement already satisfied: clang==5.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 6)) (5.0)\n",
      "Collecting click==8.0.1\n",
      "  Using cached click-8.0.1-py3-none-any.whl (97 kB)\n",
      "Collecting cloudpickle==2.0.0\n",
      "  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)\n",
      "Collecting colorama==0.4.4\n",
      "  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)\n",
      "Collecting colour==0.1.5\n",
      "  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)\n",
      "Collecting commonmark==0.9.1\n",
      "  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)\n",
      "Requirement already satisfied: cycler==0.10.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 12)) (0.10.0)\n",
      "Requirement already satisfied: dm-tree==0.1.6 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 13)) (0.1.6)\n",
      "Collecting filelock==3.2.0\n",
      "  Using cached filelock-3.2.0-py2.py3-none-any.whl (10 kB)\n",
      "Requirement already satisfied: flatbuffers==1.12 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 15)) (1.12)\n",
      "Requirement already satisfied: gast==0.4.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 16)) (0.4.0)\n",
      "Requirement already satisfied: google-auth==1.35.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 17)) (1.35.0)\n",
      "Requirement already satisfied: google-auth-oauthlib==0.4.6 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 18)) (0.4.6)\n",
      "Requirement already satisfied: google-pasta==0.2.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 19)) (0.2.0)\n",
      "Requirement already satisfied: grpcio==1.41.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 20)) (1.41.0)\n",
      "Collecting gym==0.20.0\n",
      "  Using cached gym-0.20.0.tar.gz (1.6 MB)\n",
      "Requirement already satisfied: h5py==3.1.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 22)) (3.1.0)\n",
      "Collecting idna==3.2\n",
      "  Using cached idna-3.2-py3-none-any.whl (59 kB)\n",
      "Collecting imageio==2.9.0\n",
      "  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)\n",
      "Requirement already satisfied: keras==2.6.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 25)) (2.6.0)\n",
      "Requirement already satisfied: keras-preprocessing==1.1.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 26)) (1.1.2)\n",
      "Requirement already satisfied: kiwisolver==1.3.2 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 27)) (1.3.2)\n",
      "\u001B[31mERROR: Could not find a version that satisfies the requirement libffi==3.3 (from versions: none)\u001B[0m\n",
      "\u001B[31mERROR: No matching distribution found for libffi==3.3\u001B[0m\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "metadata": {
    "id": "AjqGMn-qKwBx",
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 392
    },
    "executionInfo": {
     "status": "error",
     "timestamp": 1634657478868,
     "user_tz": -120,
     "elapsed": 420,
     "user": {
      "displayName": "",
      "photoUrl": "",
      "userId": ""
     }
    },
    "outputId": "26332e62-0879-4590-be5a-5b11cc0b4c0b",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "source": [
    "%ls\n",
    "#import helper.py\n",
    "import imp \n",
    "training = imp.new_module('src.model.training')\n",
    "exec(open(\"./src/model/training.py\").read(), training.__dict__)"
   ],
   "execution_count": null,
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "\u001B[0m\u001B[01;34mcolab\u001B[0m/  \u001B[01;34menv\u001B[0m/  README.md  requirements.txt  \u001B[01;34msrc\u001B[0m/\n"
     ]
    },
    {
     "output_type": "error",
     "ename": "ModuleNotFoundError",
     "evalue": "ignored",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mModuleNotFoundError\u001B[0m                       Traceback (most recent call last)",
      "\u001B[0;32m<ipython-input-29-ed785727ba00>\u001B[0m in \u001B[0;36m<module>\u001B[0;34m()\u001B[0m\n\u001B[1;32m      3\u001B[0m \u001B[0;32mimport\u001B[0m \u001B[0mimp\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[1;32m      4\u001B[0m \u001B[0mtraining\u001B[0m \u001B[0;34m=\u001B[0m \u001B[0mimp\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mnew_module\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0;34m'src.model.training'\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0;32m----> 5\u001B[0;31m \u001B[0mexec\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0mopen\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0;34m\"./src/model/training.py\"\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0mread\u001B[0m\u001B[0;34m(\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m,\u001B[0m \u001B[0mtraining\u001B[0m\u001B[0;34m.\u001B[0m\u001B[0m__dict__\u001B[0m\u001B[0;34m)\u001B[0m\u001B[0;34m\u001B[0m\u001B[0;34m\u001B[0m\u001B[0m\n\u001B[0m",
      "\u001B[0;32m<string>\u001B[0m in \u001B[0;36m<module>\u001B[0;34m()\u001B[0m\n",
      "\u001B[0;31mModuleNotFoundError\u001B[0m: No module named 'ray'",
      "",
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001B[0;31m---------------------------------------------------------------------------\u001B[0m\n"
     ],
     "errorDetails": {
      "actions": [
       {
        "action": "open_url",
        "actionText": "Open Examples",
        "url": "/notebooks/snippets/importing_libraries.ipynb"
       }
      ]
     }
    }
   ]
  }
 ]
}